-- Add wireframe columns to vibe_variant_plans table
-- These store the text-based wireframe descriptions generated by the LLM

ALTER TABLE vibe_variant_plans
ADD COLUMN IF NOT EXISTS wireframe_text TEXT,
ADD COLUMN IF NOT EXISTS layout_description TEXT,
ADD COLUMN IF NOT EXISTS component_list JSONB DEFAULT '[]'::jsonb;

-- Add comment for documentation
COMMENT ON COLUMN vibe_variant_plans.wireframe_text IS 'ASCII art wireframe layout generated by LLM';
COMMENT ON COLUMN vibe_variant_plans.layout_description IS 'Brief description of the layout approach';
COMMENT ON COLUMN vibe_variant_plans.component_list IS 'Array of component descriptions with placement';
